---
- name: Playbook to baseline setup
  hosts: all

  tasks:
    - name: lightdm, autologin-user
      become: yes
      copy: 
        dest: /etc/lightdm/lightdm.conf
        content: |
          [SeatDefaults]
          allow-guest=false
          autologin-guest=false
          autologin-user=ben
          autologin-user-timeout=0

#    - name: Install adblock plus addon
#      firefox_addon:
#        url: https://addons.mozilla.org/en-US/firefox/addon/adblock-plus
#        state: present

    - name: Copy /etc/systemd/logind.conf
      become: yes
      copy:
        src: logind.conf
        dest: /etc/systemd/logind.conf

#    - name: Copy /etc/firefox/syspref.js
#      become: yes
#      copy:
#        src: syspref.js
#        dest: /etc/firefox/syspref.js

#    - name: Create /etc/chromium-browser/policies/managed/ directory
#      file: path=/etc/some_directory state=directory mode=0755

    - name: Copy /etc/chromium/policies/managed/policies.json
      become: yes
      copy:
        src: policies.json
        dest: /etc/chromium/policies/managed/

    - name: Create a login user
      become: yes
      user:
        name: ben
        state: present
        system: no             # Defaults to no
        createhome: yes        # Defaults to yes



