---
- name: Playbook to cleanup-packages
  hosts: all

  tasks:
    - name: thunderbird
      become: yes
      apt: name: thunderbird purge: true state: absent

    - name: light-locker
      become: yes
      apt: name=light-locker purge=true state=absent

    - name: blueberry
      become: yes
      apt: name=blueberry purge=true state=absent

    - name: bluetooth
      become: yes
      apt: name=bluetooth purge=true state=absent

    - name: xfce4-power-manager
      become: yes
      apt: name=xfce4-power-manager purge=true state=absent

#    - name: Ansible apt purge acpid
#      become: yes
#      apt: name=acpid purge=true state=absent

#    - name: Ansible apt purge libbluetooth3
#      become: yes
#      apt: name=libbluetooth3 purge=true state=absent

    - name: Ansible apt purge libgnome-bluetooth13
      become: yes
      apt: name=libgnome-bluetooth13 purge=true state=absent

    - name: Ansible apt purge bluez-cups
      become: yes
      apt: name=bluez-cups purge=true state=absent

    - name: Ansible apt purge bluez
      become: yes
      apt: name=bluez purge=true state=absent

    - name: Ansible apt purge bluez-obexd
      become: yes
      apt: name=bluez-obexd purge=true state=absent

    - name: Ansible apt purge bluez-tools
      become: yes
      apt: name=bluez-tools purge=true state=absent

    - name: Ansible apt purge fonts-noto-cjk
      become: yes
      apt: name=fonts-noto-cjk purge=true state=absent

    - name: firefox
      become: yes
      apt: name=firefox purge=true state=absent

    - name: evolution-data-server-common
      become: yes
      apt: name=evolution-data-server-common purge=true state=absent

    - name: chromium-browser
      become: yes
      apt: name=chromium-browser state=present

    # installing nvidia-340 allow to enforce the suspend-when-lid-or-power-button-is-pushed
    - name: Ansible apt install nvidia-340
      become: yes
      apt: name=nvidia-340 state=present

    - name: Ansible apt install oneko
      become: yes
      apt: name=oneko state=present

#    - name: Update APT package cache
#      become: yes
#      apt: update_cache=yes cache_valid_time=600

#    - name: Upgrade APT to the latest packages
#      become: yes
#      apt: upgrade=dist
#      register: apt_result

    - name: Remove useless packages from the cache
      become: yes
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      become: yes
      apt:
        autoremove: yes


